from __future__ import annotations

from app.schemas.agents import AgentField, AgentSpec


def _standard_inputs() -> list[AgentField]:
    return [
        AgentField(
            key="brand_name",
            label="Brand name",
            type="string",
            required=True,
            placeholder="e.g. Nike",
        ),
        AgentField(
            key="brand_context",
            label="Brand context",
            type="string",
            required=True,
            placeholder="Describe your brand, product, and positioning in 3-5 sentences.",
        ),
    ]


def _agent(
    *,
    agent_id: str,
    name: str,
    category: str,
    summary: str,
    description: str,
    tags: list[str],
    inputs: list[AgentField],
    outputs: list[str],
    helps_with: list[str],
) -> AgentSpec:
    return AgentSpec(
        id=agent_id,
        name=name,
        category=category,
        summary=summary,
        description=description,
        tags=tags,
        inputs=[*_standard_inputs(), *inputs],
        outputs=outputs,
        helps_with=helps_with,
    )


def get_agent_specs() -> list[AgentSpec]:
    specs: list[AgentSpec] = [
        # 1. Competitive Intelligence Agent
        _agent(
            agent_id="competitive_intelligence_agent",
            name="Competitive Intelligence Agent",
            category="Competitive Strategy",
            summary="Map competitor positioning, messaging, and strategic moves.",
            description="Analyzes competitor websites, news, LinkedIn, job postings, and reviews. Delivers positioning map, messaging themes, and strategic recommendations.",
            tags=["competitive intelligence", "positioning", "market moves"],
            inputs=[
                AgentField(
                    key="competitors",
                    label="Competitors",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Nykaa, Purplle, Myntra Beauty",
                ),
                AgentField(
                    key="analysis_focus",
                    label="Analysis focus",
                    type="list[string]",
                    required=True,
                    placeholder="Positioning\nCampaigns\nProduct launches\nPricing",
                ),
                AgentField(
                    key="time_window",
                    label="Time window",
                    type="string",
                    required=True,
                    placeholder="Last 30 days / 90 days / 6 months",
                ),
                AgentField(
                    key="strategic_question",
                    label="Strategic question (optional)",
                    type="string",
                    required=False,
                    placeholder="Where are competitors investing that we are not?",
                ),
            ],
            outputs=[
                "Positioning Map",
                "Messaging Themes",
                "Recent Moves",
                "Where You Win",
                "Where Vulnerable",
                "One Strategic Move",
            ],
            helps_with=["Competitive strategy", "Positioning choices"],
        ),
        # 2. Content Agent
        _agent(
            agent_id="content_agent",
            name="Content Agent",
            category="Content & Campaigns",
            summary="Generate email, ad, and push content packs.",
            description="Builds campaign-ready copy variants with headlines, body copy, and CTAs. Each variant feels distinct and on-brand.",
            tags=["copy", "ads", "email", "content"],
            inputs=[
                AgentField(
                    key="content_type",
                    label="Content type",
                    type="list[string]",
                    required=True,
                    placeholder="Email\nAd copy\nPush\nSocial\nSMS",
                ),
                AgentField(
                    key="target_audience",
                    label="Target audience",
                    type="string",
                    required=True,
                    placeholder="Urban women 25-40, health-conscious",
                ),
                AgentField(
                    key="campaign_objective",
                    label="Campaign objective",
                    type="string",
                    required=True,
                    placeholder="Drive app downloads during festive season",
                ),
                AgentField(
                    key="tone",
                    label="Tone",
                    type="string",
                    required=True,
                    placeholder="Professional / Conversational / Bold / Witty",
                ),
                AgentField(
                    key="mandatories",
                    label="Mandatories (optional)",
                    type="string",
                    required=False,
                    placeholder="Include offer code FEST25",
                ),
            ],
            outputs=[
                "Content Variants",
                "Headlines",
                "Body Copy",
                "CTAs",
                "Creative Rationale",
            ],
            helps_with=["Campaign execution", "Copy production"],
        ),
        # 3. Brand Equity Tracker Agent
        _agent(
            agent_id="brand_equity_tracker_agent",
            name="Brand Equity Tracker Agent",
            category="Brand Strategy & Health",
            summary="Track brand health: awareness, sentiment, SOV, and AI visibility.",
            description="Delivers a CMO-ready brand health pulse with scores, risks, opportunities, and top 3 actions.",
            tags=["brand health", "sov", "awareness", "sentiment"],
            inputs=[
                AgentField(
                    key="competitors",
                    label="Competitors",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Pepsi, Thums Up",
                ),
                AgentField(
                    key="category_keywords",
                    label="Category keywords",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. cola, soft drink, refreshment",
                ),
                AgentField(
                    key="time_window",
                    label="Time window",
                    type="string",
                    required=True,
                    placeholder="Last 30 days / 90 days / 6 months",
                ),
                AgentField(
                    key="primary_concern",
                    label="Primary concern",
                    type="string",
                    required=True,
                    placeholder="Awareness / Sentiment / AI Visibility / SOV / All",
                ),
            ],
            outputs=[
                "Health Score",
                "Pulse Summary",
                "Top Risk",
                "Top Opportunity",
                "AI Visibility",
                "Brand Associations",
                "Top 3 Actions",
            ],
            helps_with=["Brand governance", "Executive reporting"],
        ),
        # 4. GEO / AI Visibility Agent
        _agent(
            agent_id="geo_agent",
            name="GEO / AI Visibility Agent",
            category="Channel & Visibility",
            summary="Assess brand presence in AI recommendations vs competitors.",
            description="Benchmarks AI visibility by platform and query intent. Delivers SOV matrix, representation accuracy, and GEO actions.",
            tags=["geo", "ai visibility", "llm search"],
            inputs=[
                AgentField(
                    key="competitors",
                    label="Competitors",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. boAt, Noise",
                ),
                AgentField(
                    key="category_queries",
                    label="Category queries",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. best wireless earphones under 2000",
                ),
                AgentField(
                    key="ai_platforms",
                    label="AI platforms",
                    type="list[string]",
                    required=True,
                    placeholder="ChatGPT\nGemini\nPerplexity\nClaude\nCopilot",
                ),
                AgentField(
                    key="visibility_goal",
                    label="Visibility goal",
                    type="string",
                    required=True,
                    placeholder="Awareness / Consideration / Recommendation / All",
                ),
            ],
            outputs=[
                "AI SOV",
                "Query Visibility",
                "Representation Accuracy",
                "Sentiment in AI",
                "Top GEO Actions",
                "GEO Health Score",
            ],
            helps_with=["AI discoverability", "GEO planning"],
        ),
        # 5. Creative Agent
        _agent(
            agent_id="creative_agent",
            name="Creative Agent",
            category="Content & Creative Generation",
            summary="Generate creative direction and concept variants.",
            description="Suggests creative territories with core ideas, insights, execution plans, headlines, and visual direction.",
            tags=["creative", "design", "campaign"],
            inputs=[
                AgentField(
                    key="campaign_brief",
                    label="Campaign brief",
                    type="string",
                    required=True,
                    placeholder="Objective, audience, key message",
                ),
                AgentField(
                    key="format",
                    label="Format",
                    type="list[string]",
                    required=True,
                    placeholder="TVC\nDigital\nOOH\nSocial\nPrint",
                ),
                AgentField(
                    key="creative_territories",
                    label="Territories",
                    type="number",
                    required=True,
                    placeholder="2 or 3",
                ),
                AgentField(
                    key="reference_brands",
                    label="Reference brands (optional)",
                    type="string",
                    required=False,
                    placeholder="Dove, Tanishq - emotional storytelling",
                ),
            ],
            outputs=[
                "Creative Territories",
                "Core Idea",
                "Insight",
                "Execution",
                "Headlines",
                "Visual Direction",
            ],
            helps_with=["Creative exploration", "Campaign direction"],
        ),
        # 6. Brand Voice Guardian Agent
        _agent(
            agent_id="brand_voice_guardian_agent",
            name="Brand Voice Guardian Agent",
            category="Brand Strategy & Health",
            summary="Audit content against voice guidelines and rewrite flagged parts.",
            description="Checks tone compliance and suggests precise brand-safe rewrites. Flags violations only.",
            tags=["brand voice", "copy audit", "tone"],
            inputs=[
                AgentField(
                    key="voice_guidelines",
                    label="Voice guidelines",
                    type="string",
                    required=True,
                    placeholder="Paste tone doc or bullet summary",
                ),
                AgentField(
                    key="content_to_audit",
                    label="Content to audit",
                    type="string",
                    required=True,
                    placeholder="Ad copy, email, social post",
                ),
                AgentField(
                    key="content_type",
                    label="Content type",
                    type="string",
                    required=True,
                    placeholder="Social / Email / Ad / Landing page / Press release",
                ),
                AgentField(
                    key="strictness",
                    label="Strictness",
                    type="string",
                    required=True,
                    placeholder="Strict / Balanced / Light touch",
                ),
            ],
            outputs=[
                "Compliance Rating",
                "Flagged Lines",
                "What Works",
                "One Recommendation",
            ],
            helps_with=["Brand consistency", "Content QA"],
        ),
        # 7. Campaign Brief Generator Agent
        _agent(
            agent_id="campaign_brief_generator_agent",
            name="Campaign Brief Generator Agent",
            category="Content & Campaigns",
            summary="Turn business goals into strategy-first creative briefs.",
            description="Builds complete briefs with insight, proposition, channels, metrics, and creative territories.",
            tags=["brief", "campaign", "creative strategy"],
            inputs=[
                AgentField(
                    key="business_objective",
                    label="Business objective",
                    type="string",
                    required=True,
                    placeholder="Drive 20% increase in trial sign-ups in Q3",
                ),
                AgentField(
                    key="target_audience",
                    label="Target audience",
                    type="string",
                    required=True,
                    placeholder="Urban women 25-40, health-conscious, SEC A",
                ),
                AgentField(
                    key="budget_range",
                    label="Budget range",
                    type="string",
                    required=True,
                    placeholder="<10L / 10-50L / 50L-1Cr / 1Cr+",
                ),
                AgentField(
                    key="campaign_duration",
                    label="Campaign duration",
                    type="string",
                    required=True,
                    placeholder="e.g. 6 weeks",
                ),
                AgentField(
                    key="channels",
                    label="Channels",
                    type="list[string]",
                    required=True,
                    placeholder="TV\nDigital\nOOH\nInfluencer\nSocial",
                ),
                AgentField(
                    key="mandatories",
                    label="Mandatories (optional)",
                    type="string",
                    required=False,
                    placeholder="Must feature new variant, festive theme",
                ),
            ],
            outputs=[
                "Campaign Objective",
                "Target Audience",
                "Consumer Insight",
                "Single Minded Proposition",
                "Reasons to Believe",
                "Channel Strategy",
                "Success Metrics",
                "Creative Territories",
            ],
            helps_with=["Brief writing", "Campaign planning"],
        ),
        # 8. Landing Page Optimisation Agent
        _agent(
            agent_id="landing_page_optimization_agent",
            name="Landing Page Optimisation Agent",
            category="Content & Creative Generation",
            summary="Audit and improve landing page conversion outcomes.",
            description="Generates conversion-focused recommendations for structure, copy, and friction reduction.",
            tags=["landing page", "cro"],
            inputs=[
                AgentField(
                    key="page_url",
                    label="Page URL",
                    type="string",
                    required=True,
                    placeholder="e.g. www.brand.com/product",
                ),
                AgentField(
                    key="conversion_goal",
                    label="Conversion goal",
                    type="string",
                    required=True,
                    placeholder="Free trial sign-up",
                ),
                AgentField(
                    key="target_audience",
                    label="Target audience",
                    type="string",
                    required=True,
                    placeholder="B2B marketers, mid-market",
                ),
                AgentField(
                    key="current_conversion_issue",
                    label="Known issue (optional)",
                    type="string",
                    required=False,
                    placeholder="High bounce on hero section",
                ),
            ],
            outputs=[
                "Conversion Audit",
                "Above the Fold",
                "Friction Points",
                "Copy Improvements",
                "Structural Recommendations",
                "Quick Win",
            ],
            helps_with=["Landing page performance", "CVR optimization"],
        ),
        # 9. Persona Research Agent
        _agent(
            agent_id="persona_research_agent",
            name="Persona Research Agent",
            category="Market & Audience Intelligence",
            summary="Build evidence-based buyer personas grounded in real consumer signals.",
            description="Creates deep personas from Reddit, reviews, forums with motivations, pain points, and buying journey.",
            tags=["persona", "consumer research", "audience"],
            inputs=[
                AgentField(
                    key="product_category",
                    label="Product category",
                    type="string",
                    required=True,
                    placeholder="e.g. Term life insurance",
                ),
                AgentField(
                    key="target_segment",
                    label="Target segment",
                    type="string",
                    required=True,
                    placeholder="First-time buyers, 28-35, urban",
                ),
                AgentField(
                    key="geography",
                    label="Geography",
                    type="string",
                    required=True,
                    placeholder="India / US / UK / SEA / Global",
                ),
                AgentField(
                    key="pain_point",
                    label="Pain point (optional)",
                    type="string",
                    required=False,
                    placeholder="Price sensitivity vs. trust",
                ),
            ],
            outputs=[
                "Persona Snapshot",
                "Motivations",
                "Frustrations",
                "Current Behaviour",
                "Switching Triggers",
                "Voice of Consumer",
                "Channels",
                "Buying Journey",
            ],
            helps_with=["Persona creation", "Audience strategy", "Message-market fit"],
        ),
        # 10. Social Listening & Sentiment Agent
        _agent(
            agent_id="social_listening_agent",
            name="Social Listening & Sentiment Agent",
            category="Market & Audience Intelligence",
            summary="Summarize market conversation signals and sentiment shifts.",
            description="Surfaces trending themes, emerging narratives, crisis signals, and engagement opportunities.",
            tags=["social", "sentiment", "listening"],
            inputs=[
                AgentField(
                    key="keywords_to_track",
                    label="Keywords to track",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Swift, Maruti Swift, #DriveYourStory",
                ),
                AgentField(
                    key="competitors",
                    label="Competitors",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Hyundai i20, Tata Altroz",
                ),
                AgentField(
                    key="time_window",
                    label="Time window",
                    type="string",
                    required=True,
                    placeholder="Last 7 days / 30 days / 90 days",
                ),
                AgentField(
                    key="platforms",
                    label="Platforms",
                    type="list[string]",
                    required=True,
                    placeholder="Twitter/X\nReddit\nInstagram\nLinkedIn\nYouTube",
                ),
            ],
            outputs=[
                "Sentiment Score",
                "Trending Themes",
                "Emerging Narratives",
                "Competitor Sentiment",
                "Crisis Signals",
                "Engagement Opportunities",
            ],
            helps_with=["Narrative monitoring", "Social strategy"],
        ),
        # 11. SEO Content Gap Agent
        _agent(
            agent_id="seo_content_gap_agent",
            name="SEO Content Gap Agent",
            category="Content & Campaigns",
            summary="Find content gaps vs competitors and generate ready briefs.",
            description="Creates SEO gap analysis with prioritized content briefs and 8-week calendar.",
            tags=["seo", "content gap", "organic growth"],
            inputs=[
                AgentField(
                    key="brand_url",
                    label="Brand URL",
                    type="string",
                    required=True,
                    placeholder="e.g. www.mamaearth.in",
                ),
                AgentField(
                    key="competitor_urls",
                    label="Competitor URLs",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. www.mcaffeine.com, www.plumgoodness.com",
                ),
                AgentField(
                    key="category_keywords",
                    label="Category keywords",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. natural skincare, paraben-free moisturiser",
                ),
                AgentField(
                    key="funnel_focus",
                    label="Funnel focus",
                    type="string",
                    required=True,
                    placeholder="Top / Mid / Bottom / All",
                ),
                AgentField(
                    key="content_formats",
                    label="Content formats",
                    type="list[string]",
                    required=True,
                    placeholder="Blog\nVideo\nLanding pages\nFAQs",
                ),
            ],
            outputs=[
                "Content Gaps",
                "Quick Wins",
                "Content Briefs",
                "Competitor Strengths",
                "8-Week Calendar",
            ],
            helps_with=["SEO roadmap", "Content planning"],
        ),
        # 12. Localisation & Cultural Fit Agent
        _agent(
            agent_id="localisation_cultural_fit_agent",
            name="Localisation & Cultural Fit Agent",
            category="Brand Strategy & Health",
            summary="Audit campaign copy for cultural fit and sensitivity before launch.",
            description="Flags non-localized messaging risks and suggests culturally resonant adaptations.",
            tags=["localization", "cultural fit", "sensitivity"],
            inputs=[
                AgentField(
                    key="campaign_copy",
                    label="Campaign copy to audit",
                    type="string",
                    required=True,
                    placeholder="Headline, body, CTA",
                ),
                AgentField(
                    key="source_market",
                    label="Source market",
                    type="string",
                    required=True,
                    placeholder="US / UK / India / Global",
                ),
                AgentField(
                    key="target_market",
                    label="Target market",
                    type="string",
                    required=True,
                    placeholder="e.g. Tamil Nadu, India or Saudi Arabia",
                ),
                AgentField(
                    key="campaign_format",
                    label="Campaign format",
                    type="string",
                    required=True,
                    placeholder="Digital / OOH / TV / Social / Email",
                ),
                AgentField(
                    key="sensitivity_areas",
                    label="Sensitivity areas (optional)",
                    type="list[string]",
                    required=False,
                    placeholder="Religion\nGender\nHumour\nPolitical\nFood",
                ),
            ],
            outputs=[
                "Fit Rating",
                "What Doesn't Translate",
                "Cultural Strengths",
                "Local Language",
                "Regulatory Flags",
                "Adapted Creative",
            ],
            helps_with=["Market expansion", "Campaign localization"],
        ),
        # 13. Customer Review Intelligence Agent
        _agent(
            agent_id="customer_review_intelligence_agent",
            name="Customer Review Intelligence Agent",
            category="Market & Audience Intelligence",
            summary="Extract unmet needs, churn signals, and sentiment trends from reviews.",
            description="Transforms fragmented review content into strategic signals and product actions.",
            tags=["reviews", "churn", "sentiment", "voc"],
            inputs=[
                AgentField(
                    key="product_name",
                    label="Product / SKU",
                    type="string",
                    required=True,
                    placeholder="e.g. Himalaya Ashwagandha Tablets",
                ),
                AgentField(
                    key="platforms",
                    label="Platforms",
                    type="list[string]",
                    required=True,
                    placeholder="Amazon\nG2\nTrustpilot\nApp Store\nReddit",
                ),
                AgentField(
                    key="focus_area",
                    label="Focus area",
                    type="string",
                    required=True,
                    placeholder="Unmet needs / Churn signals / Sentiment / All",
                ),
                AgentField(
                    key="competitor_product",
                    label="Competitor to compare (optional)",
                    type="string",
                    required=False,
                    placeholder="e.g. Dabur Shilajit",
                ),
            ],
            outputs=[
                "Praise Themes",
                "Complaint Themes",
                "Unmet Needs",
                "Voice of Consumer",
                "Sentiment Trend",
                "Churn Signals",
                "Competitive Comparison",
                "Recommendation",
            ],
            helps_with=["Product strategy", "VOC insights", "Retention"],
        ),
        # 14. Experimentation Agent
        _agent(
            agent_id="experimentation_agent",
            name="Experimentation Agent",
            category="Content & Creative Generation",
            summary="Create A/B test ideas and prioritization plans.",
            description="Builds hypothesis-led experiment plans with prioritization matrix and success metrics.",
            tags=["ab test", "experimentation", "cro"],
            inputs=[
                AgentField(
                    key="page_or_asset",
                    label="Page or asset",
                    type="string",
                    required=True,
                    placeholder="Homepage hero or Email subject line",
                ),
                AgentField(
                    key="hypothesis",
                    label="Hypothesis",
                    type="string",
                    required=True,
                    placeholder="Benefit-led headline will outperform feature-led",
                ),
                AgentField(
                    key="conversion_goal",
                    label="Conversion goal",
                    type="string",
                    required=True,
                    placeholder="Sign-up clicks",
                ),
                AgentField(
                    key="audience_segment",
                    label="Audience segment (optional)",
                    type="string",
                    required=False,
                    placeholder="Returning visitors, mobile",
                ),
            ],
            outputs=[
                "Hypothesis Quality",
                "Test Design",
                "5 A/B Test Ideas",
                "Prioritization Matrix",
                "Sample Size",
                "What Not to Test",
            ],
            helps_with=["Experiment design", "Conversion optimization"],
        ),
        # 15. Retail & Shelf Intelligence Agent
        _agent(
            agent_id="retail_shelf_intelligence_agent",
            name="Retail & Shelf Intelligence Agent",
            category="Channel & Visibility",
            summary="Audit digital shelf quality, reviews, pricing, and share of shelf.",
            description="Evaluates e-commerce listing performance and identifies quick wins.",
            tags=["retail", "ecommerce", "digital shelf"],
            inputs=[
                AgentField(
                    key="product_sku",
                    label="Product / SKU",
                    type="string",
                    required=True,
                    placeholder="e.g. Tata Sampann Chana Dal 1kg",
                ),
                AgentField(
                    key="platform",
                    label="Platform",
                    type="string",
                    required=True,
                    placeholder="Amazon India / Flipkart / Blinkit / Zepto / BigBasket",
                ),
                AgentField(
                    key="competitor_products",
                    label="Competitor products",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Fortune Chana Dal, Aashirvaad Chana Dal",
                ),
                AgentField(
                    key="category_search_term",
                    label="Category search term",
                    type="string",
                    required=True,
                    placeholder="e.g. chana dal 1kg",
                ),
            ],
            outputs=[
                "Listing Audit",
                "Review Comparison",
                "Customer Complaints",
                "Pricing Position",
                "Share of Shelf",
                "Recommendations",
            ],
            helps_with=["Shelf optimization", "Marketplace performance"],
        ),
        # 16. Market Sizing Agent
        _agent(
            agent_id="market_sizing_agent",
            name="Market Sizing Agent",
            category="Market & Audience Intelligence",
            summary="Estimate TAM/SAM/SOM with assumptions and confidence levels.",
            description="Builds practical market sizing views for planning, investor, or expansion scenarios.",
            tags=["tam", "sam", "som", "sizing"],
            inputs=[
                AgentField(
                    key="product_category",
                    label="Product category",
                    type="string",
                    required=True,
                    placeholder="e.g. Plant-based protein supplements",
                ),
                AgentField(
                    key="geography",
                    label="Geography",
                    type="string",
                    required=True,
                    placeholder="India / US / UK / SEA / Global",
                ),
                AgentField(
                    key="market_stage",
                    label="Market stage",
                    type="string",
                    required=True,
                    placeholder="Emerging / Growing / Mature",
                ),
                AgentField(
                    key="sizing_purpose",
                    label="Sizing purpose",
                    type="string",
                    required=True,
                    placeholder="Investor pitch / Internal planning / New market entry",
                ),
            ],
            outputs=[
                "TAM",
                "SAM",
                "SOM",
                "Growth Drivers",
                "Constraints",
                "Sources",
                "Confidence Level",
            ],
            helps_with=["Market entry", "Investor narratives", "Growth planning"],
        ),
        # 17. Sales Enablement Agent
        _agent(
            agent_id="sales_enablement_agent",
            name="Sales Enablement Agent",
            category="Competitive Strategy",
            summary="Generate battle cards and objection handlers for live sales calls.",
            description="Creates practical, evidence-based battlecards against specific competitors.",
            tags=["battle card", "sales", "objections"],
            inputs=[
                AgentField(
                    key="competitor",
                    label="Competitor",
                    type="string",
                    required=True,
                    placeholder="e.g. Salesforce Marketing Cloud",
                ),
                AgentField(
                    key="product_feature",
                    label="Product / feature",
                    type="string",
                    required=True,
                    placeholder="AI-powered segmentation module",
                ),
                AgentField(
                    key="buyer_persona",
                    label="Buyer persona",
                    type="string",
                    required=True,
                    placeholder="VP Marketing, mid-market B2B SaaS",
                ),
                AgentField(
                    key="top_objection",
                    label="Top objection (optional)",
                    type="string",
                    required=False,
                    placeholder="Competitor is cheaper and integrated",
                ),
            ],
            outputs=[
                "Know Your Enemy",
                "Winning Narrative",
                "Discovery Questions",
                "Objection Handlers",
                "Proof Points",
                "When to Walk Away",
            ],
            helps_with=["Sales readiness", "Competitive selling"],
        ),
        # 18. Influencer Evaluation Agent
        _agent(
            agent_id="influencer_evaluation_agent",
            name="Influencer Evaluation Agent",
            category="Channel & Visibility",
            summary="Score influencer fit and risk before budget commitment.",
            description="Evaluates audience fit, engagement quality, red flags, and collaboration recommendations.",
            tags=["influencer", "creator", "fit scoring"],
            inputs=[
                AgentField(
                    key="influencer_handles",
                    label="Influencer handles",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. @komal_pandey, @be_younicorn",
                ),
                AgentField(
                    key="platform",
                    label="Platform",
                    type="string",
                    required=True,
                    placeholder="Instagram / YouTube / LinkedIn / X / Moj",
                ),
                AgentField(
                    key="campaign_objective",
                    label="Campaign objective",
                    type="string",
                    required=True,
                    placeholder="Awareness / Consideration / Conversion / Community",
                ),
                AgentField(
                    key="budget_tier",
                    label="Budget tier",
                    type="string",
                    required=True,
                    placeholder="Nano / Micro / Macro / Mega",
                ),
                AgentField(
                    key="conflict_check",
                    label="Conflict check (optional)",
                    type="string",
                    required=False,
                    placeholder="No competitor collabs in last 6 months",
                ),
            ],
            outputs=[
                "Audience Profile",
                "Content Quality",
                "Brand Alignment",
                "Engagement Quality",
                "Past Collabs",
                "Red Flags",
                "Collaboration Format",
                "Verdict",
            ],
            helps_with=["Creator shortlisting", "Risk mitigation"],
        ),
        # 19. PR & Narrative Agent
        _agent(
            agent_id="pr_narrative_agent",
            name="PR & Narrative Agent",
            category="Content & Campaigns",
            summary="Identify timely PR angles, pitch concepts, and narrative risks.",
            description="Turns communication objectives into journalist-ready story opportunities.",
            tags=["pr", "narrative", "newsjacking"],
            inputs=[
                AgentField(
                    key="comms_objective",
                    label="Communications objective",
                    type="string",
                    required=True,
                    placeholder="Position as sustainability leader",
                ),
                AgentField(
                    key="story_type",
                    label="Story type",
                    type="string",
                    required=True,
                    placeholder="Newsjacking / Proactive pitch / Thought leadership / Crisis prep",
                ),
                AgentField(
                    key="target_media",
                    label="Target media (optional)",
                    type="string",
                    required=False,
                    placeholder="Economic Times, Mint, YourStory",
                ),
                AgentField(
                    key="news_hook",
                    label="News hook (optional)",
                    type="string",
                    required=False,
                    placeholder="World Environment Day, June 5",
                ),
            ],
            outputs=[
                "Newsjacking Opportunities",
                "Proactive Pitches",
                "Thought Leadership",
                "Narrative Risks",
                "Media Targeting",
            ],
            helps_with=["PR strategy", "Comms planning"],
        ),
        # 20. Marketing Compliance Agent
        _agent(
            agent_id="marketing_compliance_agent",
            name="Marketing Compliance Agent",
            category="Channel & Visibility",
            summary="Flag regulatory claim risks before campaign launch.",
            description="Audits ad/campaign copy for market-specific and sector-specific compliance risks.",
            tags=["compliance", "regulation", "claims"],
            inputs=[
                AgentField(
                    key="content_to_audit",
                    label="Content to audit",
                    type="string",
                    required=True,
                    placeholder="Full ad copy or script",
                ),
                AgentField(
                    key="target_market",
                    label="Target market",
                    type="string",
                    required=True,
                    placeholder="India / US / UK / EU / UAE",
                ),
                AgentField(
                    key="sector",
                    label="Sector",
                    type="string",
                    required=True,
                    placeholder="BFSI / Pharma / F&B / Edtech / FMCG / D2C / General",
                ),
                AgentField(
                    key="content_format",
                    label="Content format",
                    type="string",
                    required=True,
                    placeholder="Digital ad / TV / Influencer post / Email / OOH",
                ),
                AgentField(
                    key="specific_concern",
                    label="Specific concern (optional)",
                    type="string",
                    required=False,
                    placeholder="Is '100% natural' defensible?",
                ),
            ],
            outputs=[
                "Risk Rating",
                "Flagged Claims",
                "Required Disclosures",
                "Sector Flags",
                "What's Clean",
                "Specific Answer",
            ],
            helps_with=["Pre-launch QA", "Regulatory risk control"],
        ),
        # 21. Pricing Intelligence Agent
        _agent(
            agent_id="pricing_intelligence_agent",
            name="Pricing Intelligence Agent",
            category="Competitive Strategy",
            summary="Benchmark pricing signals and recommend pricing strategy actions.",
            description="Compares pricing posture vs. competitors and suggests near-term pricing moves.",
            tags=["pricing", "benchmark", "competitive"],
            inputs=[
                AgentField(
                    key="product_name",
                    label="Product",
                    type="string",
                    required=True,
                    placeholder="e.g. Maruti Swift ZXI+",
                ),
                AgentField(
                    key="competitors",
                    label="Competitors",
                    type="list[string]",
                    required=True,
                    placeholder="e.g. Hyundai i20 Asta, Tata Altroz XZ+",
                ),
                AgentField(
                    key="pricing_question",
                    label="Pricing question",
                    type="string",
                    required=True,
                    placeholder="Are we priced correctly for our feature set?",
                ),
                AgentField(
                    key="market",
                    label="Market",
                    type="string",
                    required=True,
                    placeholder="India / US / UK / SEA / Global",
                ),
            ],
            outputs=[
                "Price Benchmarks",
                "Positioning",
                "Value Gap",
                "Pricing Power",
                "Competitor Moves",
                "Recommendation",
                "Question Answered",
            ],
            helps_with=["Pricing strategy", "Competitive positioning"],
        ),
        # 22. Campaign QA Agent
        _agent(
            agent_id="campaign_qa_agent",
            name="Campaign QA Agent",
            category="Content & Campaigns",
            summary="Audit campaign consistency and clarity before launch.",
            description="Checks message consistency, brand fit, CTA clarity, and channel adaptation before go-live.",
            tags=["campaign qa", "copy audit", "compliance"],
            inputs=[
                AgentField(
                    key="campaign_assets",
                    label="Campaign assets",
                    type="string",
                    required=True,
                    placeholder="Paste all copy: ads, emails, social, OOH",
                ),
                AgentField(
                    key="campaign_objective",
                    label="Campaign objective",
                    type="string",
                    required=True,
                    placeholder="Drive festive sale sign-ups",
                ),
                AgentField(
                    key="target_audience",
                    label="Target audience",
                    type="string",
                    required=True,
                    placeholder="Urban millennials, 25-35",
                ),
                AgentField(
                    key="channels",
                    label="Channels",
                    type="list[string]",
                    required=True,
                    placeholder="TV\nDigital\nOOH\nSocial\nEmail",
                ),
            ],
            outputs=[
                "QA Score",
                "Message Consistency",
                "Brand Fit",
                "Audience Alignment",
                "CTA Audit",
                "Channel Adaptation",
                "Top 5 Fixes",
            ],
            helps_with=["Campaign quality assurance", "Pre-launch review"],
        ),
        # 23. Visual Identity Audit Agent
        _agent(
            agent_id="visual_identity_audit_agent",
            name="Visual Identity Audit Agent",
            category="Content & Creative Generation",
            summary="Assess visual consistency across brand touchpoints.",
            description="Audits visual identity consistency and recommends fixes for stronger brand cohesion.",
            tags=["visual identity", "design", "brand consistency"],
            inputs=[
                AgentField(
                    key="brand_url",
                    label="Brand URL",
                    type="string",
                    required=True,
                    placeholder="e.g. www.brand.com",
                ),
                AgentField(
                    key="social_handles",
                    label="Social handles",
                    type="string",
                    required=True,
                    placeholder="@brandname on Instagram, LinkedIn",
                ),
                AgentField(
                    key="visual_guidelines",
                    label="Visual guidelines (optional)",
                    type="string",
                    required=False,
                    placeholder="Paste brand visual standards summary",
                ),
                AgentField(
                    key="audit_focus",
                    label="Audit focus",
                    type="list[string]",
                    required=True,
                    placeholder="Logo\nColor\nTypography\nImagery\nSocial\nWebsite",
                ),
            ],
            outputs=[
                "Consistency Scores",
                "What's Working",
                "Inconsistencies",
                "Distinctive Assets",
                "vs Competitors",
                "Top 3 Fixes",
            ],
            helps_with=["Visual brand governance", "Design consistency"],
        ),
        # 24. Legacy Competitor Intelligence Agent
        _agent(
            agent_id="competitor_intelligence_legacy_agent",
            name="Competitor Intelligence Agent (Legacy)",
            category="Competitive Strategy",
            summary="Legacy single-competitor scorecard and recommendations.",
            description="Lightweight competitor analysis for teams using the legacy flow. Upgrade to Competitive Intelligence Agent for multi-competitor analysis.",
            tags=["competitor", "legacy", "scorecard"],
            inputs=[
                AgentField(
                    key="competitor",
                    label="Competitor",
                    type="string",
                    required=True,
                    placeholder="e.g. Purplle",
                ),
                AgentField(
                    key="focus",
                    label="Focus",
                    type="string",
                    required=True,
                    placeholder="Positioning / Pricing / Product / Campaigns",
                ),
            ],
            outputs=[
                "Scorecard",
                "Key Differentiators",
                "Key Vulnerabilities",
                "Strategic Implication",
            ],
            helps_with=["Legacy workflows"],
        ),
    ]
    return specs
